spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/merchant
    username: postgres
    password: postgres
    pool:
      initial-size: 50
      max-size: 100
      max-idle-time: 30m
      max-life-time: 2m
      max-create-connection-time: 30s
      validation-query: SELECT 1
  data:
    redis:
      timeout: 5000
      host: localhost
      port: 6379
springdoc:
    swagger-ui:
        path: /swagger-ui.html

